CODE_TO_NAME: dict[str, str] = {
    "AD": "Andorra", "AE": "United Arab Emirates", "AF": "Afghanistan",
    "AG": "Antigua and Barbuda", "AI": "Anguilla", "AL": "Albania",
    "AM": "Armenia", "AN": "Netherlands Antilles", "AO": "Angola",
    "AR": "Argentina", "AS": "American Samoa", "AT": "Austria",
    "AU": "Australia", "AW": "Aruba", "AY": "Anguilla", "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina", "BB": "Barbados", "BC": "Bonaire",
    "BD": "Bangladesh", "BE": "Belgium", "BF": "Burkina Faso",
    "BG": "Bulgaria", "BH": "Bahrain", "BI": "Burundi", "BJ": "Benin",
    "BM": "Bermuda", "BN": "Brunei", "BO": "Bolivia", "BQ": "Bonaire",
    "BR": "Brazil", "BS": "Bahamas", "BT": "Bhutan", "BU": "Burma",
    "BW": "Botswana", "BX": "Bonaire", "BY": "Belarus", "BZ": "Belize",
    "CA": "Canada", "CB": "Cambodia", "CD": "DR Congo", "CE": "Sri Lanka",
    "CF": "Central African Republic", "CG": "Congo", "CH": "Switzerland",
    "CI": "Ivory Coast", "CJ": "Cayman Islands", "CK": "Cook Islands",
    "CL": "Chile", "CM": "Cameroon", "CN": "China", "CO": "Colombia",
    "CR": "Costa Rica", "CS": "Czechoslovakia", "CU": "Cuba",
    "CV": "Cape Verde", "CW": "Curacao", "CY": "Cyprus", "CZ": "Czechia",
    "DD": "East Germany", "DE": "Germany", "DH": "Dominica",
    "DI": "Djibouti", "DJ": "Djibouti", "DK": "Denmark", "DM": "Dominica",
    "DO": "Dominican Republic", "DS": "Dominica", "DY": "Benin",
    "DZ": "Algeria", "EC": "Ecuador", "EE": "Estonia", "EG": "Egypt",
    "EI": "Ireland", "EM": "Eswatini", "EN": "England", "ER": "Eritrea",
    "ES": "Spain", "ET": "Ethiopia", "FC": "Faroe Islands", "FI": "Finland",
    "FJ": "Fiji", "FN": "Finland", "FO": "Faroe Islands", "FR": "France",
    "FS": "FS Micronesia", "FT": "French Guiana", "GA": "Gabon",
    "GC": "Grenada", "GD": "Grenada", "GE": "Georgia", "GF": "French Guiana",
    "GH": "Ghana", "GI": "Gibraltar", "GM": "Gambia", "GN": "Guinea",
    "GP": "Guadeloupe", "GQ": "Equatorial Guinea", "GR": "Greece",
    "GT": "Guatemala", "GU": "Guam", "GW": "Guinea-Bissau", "GY": "Guyana",
    "HA": "Haiti", "HK": "Hong Kong", "HN": "Honduras", "HR": "Croatia",
    "HT": "Haiti", "HU": "Hungary", "ID": "Indonesia", "IE": "Ireland",
    "IL": "Israel", "IN": "India", "IQ": "Iraq", "IR": "Iran",
    "IS": "Iceland", "IT": "Italy", "JM": "Jamaica", "JO": "Jordan",
    "JP": "Japan", "KA": "Kazakhstan", "KD": "Kurdistan",
    "KE": "Kenya", "KG": "Kyrgyzstan", "KH": "Cambodia", "KM": "Comoros",
    "KN": "Saint Kitts and Nevis", "KO": "Kosovo", "KP": "North Korea",
    "KR": "South Korea", "KU": "Kuwait", "KW": "Kuwait", "KY": "Kyrgyzstan",
    "KZ": "Kazakhstan", "LA": "Laos", "LB": "Lebanon", "LC": "Saint Lucia",
    "LI": "Liechtenstein", "LK": "Sri Lanka", "LR": "Liberia",
    "LS": "Lesotho", "LT": "Lithuania", "LU": "Luxembourg", "LV": "Latvia",
    "LY": "Libya", "MA": "Morocco", "MD": "Moldova", "ME": "Montenegro",
    "MF": "Saint Martin", "MG": "Madagascar", "MI": "Northern Mariana Islands",
    "MK": "North Macedonia", "ML": "Mali", "MM": "Myanmar", "MN": "Mongolia",
    "MO": "Macao", "MQ": "Martinique", "MR": "Mauritania", "MS": "Montserrat",
    "MT": "Malta", "MU": "Mauritius", "MV": "Maldives", "MW": "Malawi",
    "MX": "Mexico", "MY": "Malaysia", "MZ": "Mozambique",
    "NC": "New Caledonia", "ND": "Niger", "NE": "Niger", "NG": "Nigeria",
    "NH": "Vanuatu", "NI": "Nicaragua", "NL": "Netherlands", "NM": "Namibia",
    "NN": "Northern Cyprus", "NO": "Norway", "NP": "Nepal",
    "NS": "Suriname", "NV": "Niue", "NY": "Libya", "NZ": "New Zealand",
    "OM": "Oman", "OR": "Reunion", "PA": "Panama", "PE": "Peru",
    "PG": "Papua New Guinea", "PH": "Philippines", "PK": "Pakistan",
    "PL": "Poland", "PR": "Puerto Rico", "PS": "Palestine", "PT": "Portugal",
    "PY": "Paraguay", "QA": "Qatar", "RE": "Reunion", "RG": "Guinea",
    "RH": "Zimbabwe", "RM": "Madagascar", "RO": "Romania", "RR": "Aruba",
    "RS": "Serbia", "RU": "Russia", "RV": "Ivory Coast", "RW": "Rwanda",
    "SA": "Saudi Arabia", "SB": "Solomon Islands", "SC": "Seychelles",
    "SD": "Sudan", "SE": "Sweden", "SG": "Singapore", "SI": "Slovenia",
    "SK": "Slovakia", "SL": "Sierra Leone", "SM": "San Marino",
    "SN": "Senegal", "SO": "Somalia", "SP": "Spain", "SQ": "Albania",
    "SR": "Suriname", "SS": "South Sudan", "ST": "Sao Tome and Principe",
    "SU": "Soviet Union", "SV": "El Salvador", "SW": "Sweden",
    "SX": "Sint Maarten", "SY": "Syria", "SZ": "Eswatini",
    "TD": "Chad", "TG": "Togo", "TH": "Thailand", "TI": "Tajikistan",
    "TJ": "Tajikistan", "TL": "East Timor", "TM": "Turkmenistan",
    "TN": "Tunisia", "TO": "Tonga", "TR": "Turkey", "TT": "Trinidad and Tobago",
    "TW": "Taiwan", "TY": "Tahiti", "TZ": "Tanzania",
    "UA": "Ukraine", "UG": "Uganda", "UH": "Hungary", "UM": "United States",
    "US": "United States", "UV": "Burkina Faso", "UY": "Uruguay",
    "UZ": "Uzbekistan", "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela", "VG": "British Virgin Islands", "VI": "US Virgin Islands",
    "VN": "Vietnam", "VU": "Vanuatu", "WA": "Wallis and Futuna",
    "WG": "West Germany", "WM": "Western Sahara", "WS": "Samoa",
    "YE": "Yemen", "YU": "Yugoslavia", "ZA": "South Africa",
    "ZD": "Zanzibar", "ZM": "Zambia", "ZR": "DR Congo", "ZW": "Zimbabwe",
}

NAME_TO_CODE: dict[str, str] = {v: k for k, v in CODE_TO_NAME.items()}
